# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ioam_trace.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ioam_trace.proto',
  package='ioam_trace',
  syntax='proto3',
  serialized_options=b'Z\014.;ioam_trace',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10ioam_trace.proto\x12\nioam_trace\x1a\x1bgoogle/protobuf/empty.proto\"\x92\x01\n\tIOAMTrace\x12\x14\n\x0cTraceId_High\x18\x01 \x01(\x06\x12\x13\n\x0bTraceId_Low\x18\x02 \x01(\x06\x12\x0e\n\x06SpanId\x18\x03 \x01(\x06\x12\x13\n\x0bNamespaceId\x18\x04 \x01(\r\x12\x10\n\x08\x42itField\x18\x05 \x01(\x07\x12#\n\x05Nodes\x18\x06 \x03(\x0b\x32\x14.ioam_trace.IOAMNode\"-\n\x0bOpaqueState\x12\x10\n\x08SchemaId\x18\x01 \x01(\r\x12\x0c\n\x04\x44\x61ta\x18\x02 \x01(\x0c\"\xae\x02\n\x08IOAMNode\x12\x10\n\x08HopLimit\x18\x01 \x01(\r\x12\x0c\n\x02Id\x18\x02 \x01(\rH\x00\x12\x10\n\x06WideId\x18\x03 \x01(\x04H\x00\x12\x11\n\tIngressId\x18\x04 \x01(\r\x12\x10\n\x08\x45gressId\x18\x05 \x01(\r\x12\x11\n\tTimestamp\x18\x06 \x01(\r\x12\x14\n\x0cTimestampSub\x18\x07 \x01(\r\x12\x14\n\x0cTransitDelay\x18\x08 \x01(\r\x12\x14\n\x0c\x45gressQDepth\x18\t \x01(\r\x12\x17\n\x0f\x42ufferOccupancy\x18\n \x01(\r\x12\x0e\n\x04\x44\x61ta\x18\x0b \x01(\x0cH\x01\x12\x12\n\x08WideData\x18\x0c \x01(\x0cH\x01\x12$\n\x03OSS\x18\r \x01(\x0b\x32\x17.ioam_trace.OpaqueStateB\x06\n\x04NodeB\x0b\n\tNamespace2H\n\x0bIOAMService\x12\x39\n\x06Report\x12\x15.ioam_trace.IOAMTrace\x1a\x16.google.protobuf.Empty\"\x00\x42\x0eZ\x0c.;ioam_traceb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_IOAMTRACE = _descriptor.Descriptor(
  name='IOAMTrace',
  full_name='ioam_trace.IOAMTrace',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='TraceId_High', full_name='ioam_trace.IOAMTrace.TraceId_High', index=0,
      number=1, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='TraceId_Low', full_name='ioam_trace.IOAMTrace.TraceId_Low', index=1,
      number=2, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='SpanId', full_name='ioam_trace.IOAMTrace.SpanId', index=2,
      number=3, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='NamespaceId', full_name='ioam_trace.IOAMTrace.NamespaceId', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='BitField', full_name='ioam_trace.IOAMTrace.BitField', index=4,
      number=5, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Nodes', full_name='ioam_trace.IOAMTrace.Nodes', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=208,
)


_OPAQUESTATE = _descriptor.Descriptor(
  name='OpaqueState',
  full_name='ioam_trace.OpaqueState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='SchemaId', full_name='ioam_trace.OpaqueState.SchemaId', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Data', full_name='ioam_trace.OpaqueState.Data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=210,
  serialized_end=255,
)


_IOAMNODE = _descriptor.Descriptor(
  name='IOAMNode',
  full_name='ioam_trace.IOAMNode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='HopLimit', full_name='ioam_trace.IOAMNode.HopLimit', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Id', full_name='ioam_trace.IOAMNode.Id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='WideId', full_name='ioam_trace.IOAMNode.WideId', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='IngressId', full_name='ioam_trace.IOAMNode.IngressId', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='EgressId', full_name='ioam_trace.IOAMNode.EgressId', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Timestamp', full_name='ioam_trace.IOAMNode.Timestamp', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='TimestampSub', full_name='ioam_trace.IOAMNode.TimestampSub', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='TransitDelay', full_name='ioam_trace.IOAMNode.TransitDelay', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='EgressQDepth', full_name='ioam_trace.IOAMNode.EgressQDepth', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='BufferOccupancy', full_name='ioam_trace.IOAMNode.BufferOccupancy', index=9,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Data', full_name='ioam_trace.IOAMNode.Data', index=10,
      number=11, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='WideData', full_name='ioam_trace.IOAMNode.WideData', index=11,
      number=12, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='OSS', full_name='ioam_trace.IOAMNode.OSS', index=12,
      number=13, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='Node', full_name='ioam_trace.IOAMNode.Node',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='Namespace', full_name='ioam_trace.IOAMNode.Namespace',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=258,
  serialized_end=560,
)

_IOAMTRACE.fields_by_name['Nodes'].message_type = _IOAMNODE
_IOAMNODE.fields_by_name['OSS'].message_type = _OPAQUESTATE
_IOAMNODE.oneofs_by_name['Node'].fields.append(
  _IOAMNODE.fields_by_name['Id'])
_IOAMNODE.fields_by_name['Id'].containing_oneof = _IOAMNODE.oneofs_by_name['Node']
_IOAMNODE.oneofs_by_name['Node'].fields.append(
  _IOAMNODE.fields_by_name['WideId'])
_IOAMNODE.fields_by_name['WideId'].containing_oneof = _IOAMNODE.oneofs_by_name['Node']
_IOAMNODE.oneofs_by_name['Namespace'].fields.append(
  _IOAMNODE.fields_by_name['Data'])
_IOAMNODE.fields_by_name['Data'].containing_oneof = _IOAMNODE.oneofs_by_name['Namespace']
_IOAMNODE.oneofs_by_name['Namespace'].fields.append(
  _IOAMNODE.fields_by_name['WideData'])
_IOAMNODE.fields_by_name['WideData'].containing_oneof = _IOAMNODE.oneofs_by_name['Namespace']
DESCRIPTOR.message_types_by_name['IOAMTrace'] = _IOAMTRACE
DESCRIPTOR.message_types_by_name['OpaqueState'] = _OPAQUESTATE
DESCRIPTOR.message_types_by_name['IOAMNode'] = _IOAMNODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IOAMTrace = _reflection.GeneratedProtocolMessageType('IOAMTrace', (_message.Message,), {
  'DESCRIPTOR' : _IOAMTRACE,
  '__module__' : 'ioam_trace_pb2'
  # @@protoc_insertion_point(class_scope:ioam_trace.IOAMTrace)
  })
_sym_db.RegisterMessage(IOAMTrace)

OpaqueState = _reflection.GeneratedProtocolMessageType('OpaqueState', (_message.Message,), {
  'DESCRIPTOR' : _OPAQUESTATE,
  '__module__' : 'ioam_trace_pb2'
  # @@protoc_insertion_point(class_scope:ioam_trace.OpaqueState)
  })
_sym_db.RegisterMessage(OpaqueState)

IOAMNode = _reflection.GeneratedProtocolMessageType('IOAMNode', (_message.Message,), {
  'DESCRIPTOR' : _IOAMNODE,
  '__module__' : 'ioam_trace_pb2'
  # @@protoc_insertion_point(class_scope:ioam_trace.IOAMNode)
  })
_sym_db.RegisterMessage(IOAMNode)


DESCRIPTOR._options = None

_IOAMSERVICE = _descriptor.ServiceDescriptor(
  name='IOAMService',
  full_name='ioam_trace.IOAMService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=562,
  serialized_end=634,
  methods=[
  _descriptor.MethodDescriptor(
    name='Report',
    full_name='ioam_trace.IOAMService.Report',
    index=0,
    containing_service=None,
    input_type=_IOAMTRACE,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_IOAMSERVICE)

DESCRIPTOR.services_by_name['IOAMService'] = _IOAMSERVICE

# @@protoc_insertion_point(module_scope)
